version: '3.1'

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: shivaanta
    networks:
      - net
  app:
    image: myapp:latest
    build: ./
    ports:
      - "80:8081"
    environment:
      DATABASE: db
    depends_on:
      - db
    networks:
      - net

networks:
  net: